name: Build app
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Inserisci il nome della branch"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repository code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Execute build
        run: yarn build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install
        
      - name: test code
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write     
      id-token: write
      
    environment:
        name: production
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: install dependencies
        run: npm install

      - name: execute build
        run: npm run build

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./out"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
